language: node_js
notifications:
  email: false
node_js:
  - 14
before_install:
  - npm i -g npm@^6.14.8
install:
  - npm install
before_script:
  - npm prune
script:
  - npm run lint
  - npm run test
after_success:
  - npm run semantic-release
